name: Install SANDY with test dependencies
description: Installs the SANDY package with test extras

runs:
  using: "composite"
  steps:
    - name: Install SANDY
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        pip install --no-cache-dir .[test]
