language: python

dist: xenial

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - cmake
      - git

env:
  - NJOY=${TRAVIS_BUILD_DIR}/NJOY2016/build/njoy

python:
  - "3.6"

branches:
  except: gh-pages

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install sphinx sphinx_rtd_theme codecov numpydoc coveralls pytest-cov
  - pip install -r requirements_pip.txt

install:
  - which python3 python
  - echo $PATH
  - git clone https://github.com/njoy/NJOY2016.git && (cd NJOY2016 && mkdir build && cd build && cmake -DPython3_EXECUTABLE=$(which python3) .. && make) # install NJOY
  - rm -rf NJOY2016/tests
  - python setup.py install

script:
  - pytest --cov=sandy/

after_success:
  - coveralls

# Set up sphinx configuration file and produce SANDY documentation in html.
before_deploy:
  - bash make_docs.sh html

# Deploy SANDY docs to gihub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "api_docs/build/html"
  keep-history: false
  overwrite: true
  on:
    branch: develop
