language: python
addons:
  apt:
    packages:
      - gfortran
script:
  - make
python:
  - "3.6"
before_install:
  - pip install sphinx sphinx_rtd_theme
  - python setup.py install
job:
  include:
    - stage: test
      name: "Run pytest"
      script: pytest
    - stage: deploy
      name: "Deploy docs to gh-pages"
      script: sphinx-build docs docs/html -b html
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: "docs/html"
        keep-history: true
        overwrite: true
        on:
          branch: master
