language: python
before_script:
  - sudo apt-get install gfortran
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - test $TRAVIS_BRANCH = "devel" && pytest -s  -v --basetemp=sandy_tests -m "not slow"
