language: python
addons:
  apt:
    packages:
      - gfortran
python:
  - "3.6"
before_install:
  - pip install sphinx sphinx_rtd_theme
install:
  - python setup.py install
script:
  - pytest
before_deploy:
  - sphinx-apidoc -F -E -f -o html sandy -A "Luca Fiorito" -H "SANDY" -V 1 -R 0 --ext-githubpages --ext-mathjax
  - cd html && make html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "html/_build/html"
  keep-history: true
  overwrite: true
  on:
    branch: master
# sphinx-apidoc -F -E -f -o html sandy -A "Luca Fiorito" -H "SANDY" -V 1 -R 0 --ext-githubpages --ext-mathjax
