[metadata]
name = sandy
version = attr: sandy.__version__
author = Luca Fiorito
author_email = lucafiorito.11@gmail.com
url = https://github.com/luca-fiorito-11/sandy
description = SANDY: sampling of nuclear data and uncertainty
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
zip_safe = False
include_package_data = True
packages = find:
python_requires = >=3.7
install_requires =
    numpy
    scipy
    pandas
    pyyaml
    openpyxl
    tqdm>=4.0.0

[options.extras_require]
test =
    numpydoc
    nbval
    codecov
    coveralls
    pytest-cov

notebook =
    jupyterlab
    notebook
    matplotlib
    seaborn
    scikit-learn
    serpentTools

doc =
    sphinx
    sphinx_rtd_theme


[options.packages.find]
# Exclude heavy dirs and *all* appendix subpackages from being treated as Python packages.
# exclude = sandy.appendix.* tells setuptools: “do not treat any sandy.appendix.<something> as a package.”
exclude =
    sandy.appendix
    sandy.appendix.*
    sandy.appendix.libraries
    notebooks*

[options.package_data]
# Ship data + smoke tests in the wheel
sandy =
    appendix/onefile_archives/*.tar.xz
    appendix/chain_yields/*.txt
    appendix/fycorr/.tar.xz
