name: Setup NJOY2016
description: Clone and build NJOY2016

runs:
  using: "composite"
  steps:
    - name: Clone NJOY2016
      shell: bash
      run: |
        git clone https://github.com/njoy/NJOY2016.git

    - name: Build NJOY2016
      shell: bash
      run: |
        cd NJOY2016
        mkdir -p build && cd build
        cmake .. \
          -DPython3_EXECUTABLE=$(which python3) \
          -DCMAKE_Fortran_FLAGS="-w" \  # suppress fortran warnings
          -DCMAKE_CXX_FLAGS="-w" \
          -DCMAKE_C_FLAGS="-w"
        make -s

    - name: Remove NJOY2016 tests
      shell: bash
      run: rm -rf NJOY2016/tests
