name: Notebook CI

on:
  schedule:
    - cron: '30 14 * * 1,3,5'  # Mon, Wed, Fri at 14:30 UTC
  workflow_dispatch:

env:
  NJOY: ${{ github.workspace }}/NJOY2016/build/njoy
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ">=3.8 <3.12"  # to comply with serpentTools

      - name: Set up NJOY2016
        uses: ./.github/actions/setup-njoy

      - name: Install SANDY with all extras
        uses: ./.github/actions/install-sandy-local-extras
        # Installs package with test extras

      - name: Execute Jupyter notebooks
        run: |
          cd notebooks
          mkdir -p executed_notebooks
          jupyter nbconvert --to notebook --execute *.ipynb \
            --ExecutePreprocessor.kernel_name='python3' --inplace > /dev/null  # suppress NJOY output
          mv *.ipynb executed_notebooks/

      - name: Push executed notebooks to external repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: notebooks/executed_notebooks/
          destination-github-username: 'luca-fiorito-11'
          destination-repository-name: 'sandy_notebooks'
          user-email: lucafiorito.11@gmail.com
          commit-message: pushing notebooks...
          target-branch: executed_notebooks_v1.1
