name: Notebook CI

on:
  schedule:
    - cron: '30 14 * * 1'  # Mon, Wed, Fri at 14:30 UTC
  workflow_dispatch:

env:
  NJOY: ${{ github.workspace }}/NJOY2016/build/njoy
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  execute_batch_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.8 <3.12"  # to comply with serpentTools

      - name: Set up NJOY2016
        uses: ./.github/actions/setup-njoy

      - name: Install SANDY with all extras
        uses: ./.github/actions/install-sandy-local-extras

      - name: Execute notebooks in batch_1
        run: |
          cd notebooks/batch_1
          mkdir -p executed
          jupyter nbconvert --to notebook --execute *.ipynb \
            --ExecutePreprocessor.kernel_name='python3' --inplace > /dev/null
          mv *.ipynb executed/

      - name: Upload executed notebooks from batch_1
        uses: actions/upload-artifact@v4
        with:
          name: executed_batch_1
          path: notebooks/batch_1/executed/

  execute_batch_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.8 <3.12"  # to comply with serpentTools

      - name: Set up NJOY2016
        uses: ./.github/actions/setup-njoy

      - name: Install SANDY with all extras
        uses: ./.github/actions/install-sandy-local-extras

      - name: Execute notebooks in batch_2
        run: |
          cd notebooks/batch_2
          mkdir -p executed
          jupyter nbconvert --to notebook --execute *.ipynb \
            --ExecutePreprocessor.kernel_name='python3' --inplace > /dev/null
          mv *.ipynb executed/

      - name: Upload executed notebooks from batch_2
        uses: actions/upload-artifact@v4
        with:
          name: executed_batch_2
          path: notebooks/batch_2/executed/

  execute_batch_3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.8 <3.12"  # to comply with serpentTools

      - name: Set up NJOY2016
        uses: ./.github/actions/setup-njoy

      - name: Install SANDY with all extras
        uses: ./.github/actions/install-sandy-local-extras

      - name: Execute notebooks in batch_3
        run: |
          cd notebooks/batch_3
          mkdir -p executed
          jupyter nbconvert --to notebook --execute *.ipynb \
            --ExecutePreprocessor.kernel_name='python3' --inplace > /dev/null
          mv *.ipynb executed/

      - name: Upload executed notebooks from batch_3
        uses: actions/upload-artifact@v4
        with:
          name: executed_batch_3
          path: notebooks/batch_3/executed/

  execute_batch_4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.8 <3.12"  # to comply with serpentTools

      - name: Set up NJOY2016
        uses: ./.github/actions/setup-njoy

      - name: Install SANDY with all extras
        uses: ./.github/actions/install-sandy-local-extras

      - name: Execute notebooks in batch_4
        run: |
          cd notebooks/batch_4
          mkdir -p executed
          jupyter nbconvert --to notebook --execute *.ipynb \
            --ExecutePreprocessor.kernel_name='python3' --inplace > /dev/null
          mv *.ipynb executed/

      - name: Upload executed notebooks from batch_4
        uses: actions/upload-artifact@v4
        with:
          name: executed_batch_4
          path: notebooks/batch_4/executed/

  execute_batch_5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.8 <3.12"  # to comply with serpentTools

      - name: Set up NJOY2016
        uses: ./.github/actions/setup-njoy

      - name: Install SANDY with all extras
        uses: ./.github/actions/install-sandy-local-extras

      - name: Execute notebooks in batch_5
        run: |
          cd notebooks/batch_5
          mkdir -p executed
          jupyter nbconvert --to notebook --execute *.ipynb \
            --ExecutePreprocessor.kernel_name='python3' --inplace > /dev/null
          mv *.ipynb executed/

      - name: Upload executed notebooks from batch_5
        uses: actions/upload-artifact@v4
        with:
          name: executed_batch_5
          path: notebooks/batch_5/executed/

  push_notebooks:
    needs: [execute_batch_1, execute_batch_2, execute_batch_3, execute_batch_4, execute_batch_5]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executed notebooks from batch_1
        uses: actions/download-artifact@v4
        with:
          name: executed_batch_1
          path: notebooks/batch_1/executed/

      - name: Download executed notebooks from batch_2
        uses: actions/download-artifact@v4
        with:
          name: executed_batch_2
          path: notebooks/batch_2/executed/

      - name: Download executed notebooks from batch_3
        uses: actions/download-artifact@v4
        with:
          name: executed_batch_3
          path: notebooks/batch_3/executed/

      - name: Download executed notebooks from batch_4
        uses: actions/download-artifact@v4
        with:
          name: executed_batch_4
          path: notebooks/batch_4/executed/

      - name: Download executed notebooks from batch_5
        uses: actions/download-artifact@v4
        with:
          name: executed_batch_5
          path: notebooks/batch_5/executed/

      - name: Flatten executed notebooks into a single directory
        run: |
          mkdir -p notebooks_flat
          mv notebooks/batch_1/executed/*.ipynb notebooks_flat/
          mv notebooks/batch_2/executed/*.ipynb notebooks_flat/
          mv notebooks/batch_3/executed/*.ipynb notebooks_flat/
          mv notebooks/batch_4/executed/*.ipynb notebooks_flat/
          mv notebooks/batch_5/executed/*.ipynb notebooks_flat/

      - name: Push all executed notebooks
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: notebooks_flat/
          destination-github-username: 'luca-fiorito-11'
          destination-repository-name: 'sandy_notebooks'
          user-email: lucafiorito.11@gmail.com
          commit-message: pushing all executed notebooks...
          target-branch: executed_notebooks_v1.1

